export enum Api {
  Oficinas = 'oficinas',
  Bodegas = 'bodegas',
  Productos = 'productos',
  UnidadesDeMedida = 'unimedidas',
  Comercios = 'comercios',
  BodegasPorComercio = 'comercio-bodegas',
  ConfiguracionDeUnComercio = 'confcomercio',
  AperturasDeUnComercio = 'comercioaperturas',
  DetallesDeAperturaDeUnComercio = 'comercioaperturasdetalles',
  TiketsPorEstadoDeApertura = 'tickapertura',
  EstadosDeEntregaDeUnComercio = 'analisis-entregas',
  PertenenciaConsumidorNucleoCI = 'consumidornucleoci',
  PertenenciaConsumidorNucleoID = 'consumidornucleoid',
  PertenenciaComercioNucleoCI = 'consumidorcomercioci',
  PertenenciaComercioNucleoID = 'consumidorcomercioid',
  InformacionDelConsumidorPorCi = 'infconsumidorcomercioci',
  InformacionDelConsumidorPorID = 'infconsumidorcomercioid',
  ConsumidoresPorBodega = 'consumidoresbodega',
}
